<a href="https://colab.research.google.com/github/siddharthchd/Introduction_to_Data_Science/blob/master/week3/week3_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Merging Dataframes

In [ ]:
import pandas as pd

df  = pd.DataFrame([{'Name' : 'Chris', 'Item Purchased' : 'Sponge', 'Cost' : 22.50},
                    {'Name' : 'Kevyn', 'Item Purchased' : 'Kitty Litter', 'Cost' : 2.50},
                    {'Name' : 'Filip', 'Item Purchased' : 'Spoon', 'Cost' : 5.00}],
                   index = ['Store 1', 'Store 2', 'Store 3'])
df

          Name Item Purchased  Cost
Store 1  Chris         Sponge  22.5
Store 2  Kevyn   Kitty Litter   2.5
Store 3  Filip          Spoon   5.0

In [ ]:
df['Date'] = ['December 1', 'January 1', 'mid-May']
df

          Name Item Purchased  Cost        Date
Store 1  Chris         Sponge  22.5  December 1
Store 2  Kevyn   Kitty Litter   2.5   January 1
Store 3  Filip          Spoon   5.0     mid-May

In [ ]:
df['Feedback'] = ['Positive', None, 'Negative']
df

          Name Item Purchased  Cost        Date  Feedback
Store 1  Chris         Sponge  22.5  December 1  Positive
Store 2  Kevyn   Kitty Litter   2.5   January 1      None
Store 3  Filip          Spoon   5.0     mid-May  Negative

In [ ]:
adf = df.reset_index()
adf['Date'] = pd.Series({0 : 'December 1', 2 : 'mid-May'})
adf

     index   Name Item Purchased  Cost        Date  Feedback
0  Store 1  Chris         Sponge  22.5  December 1  Positive
1  Store 2  Kevyn   Kitty Litter   2.5         NaN      None
2  Store 3  Filip          Spoon   5.0     mid-May  Negative

In [ ]:
staff_df = pd.DataFrame([{'Name' : 'Kelly', 'Role' : 'Director of HR'},
                         {'Name' : 'Sally', 'Role' : 'Course liason'},
                         {'Name' : 'James', 'Role' : 'Grader'}])
staff_df = staff_df.set_index('Name')

student_df = pd.DataFrame([{'Name' : 'James', 'School' : 'Business'},
                           {'Name' : 'Mike', 'School' : 'Law'},
                           {'Name' : 'Sally', 'School' : 'Engineering'}])
student_df = student_df.set_index('Name')

print(staff_df.head())
print()
print(student_df.head())

                 Role
Name
Kelly  Director of HR
Sally   Course liason
James          Grader

            School
Name
James     Business
Mike           Law
Sally  Engineering

In [ ]:
pd.merge(staff_df, student_df, how = 'outer', left_index = True, right_index = True)

                 Role       School
Name
James          Grader     Business
Kelly  Director of HR          NaN
Mike              NaN          Law
Sally   Course liason  Engineering

In [ ]:
pd.merge(staff_df, student_df, how = 'left', left_index = True, right_index = True)

                 Role       School
Name
Kelly  Director of HR          NaN
Sally   Course liason  Engineering
James          Grader     Business

In [ ]:
pd.merge(staff_df, student_df, how = 'right', left_index = True, right_index = True)

                Role       School
Name
James         Grader     Business
Mike             NaN          Law
Sally  Course liason  Engineering

In [ ]:
staff_df= staff_df.reset_index()
student_df = student_df.reset_index()
pd.merge(staff_df, student_df, how = 'left', left_on = 'Name', right_on = 'Name')

    Name            Role       School
0  Kelly  Director of HR          NaN
1  Sally   Course liason  Engineering
2  James          Grader     Business

In [ ]:
staff_df = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR', 'Location': 'State Street'},
                         {'Name': 'Sally', 'Role': 'Course liasion', 'Location': 'Washington Avenue'},
                         {'Name': 'James', 'Role': 'Grader', 'Location': 'Washington Avenue'}])
student_df = pd.DataFrame([{'Name': 'James', 'School': 'Business', 'Location': '1024 Billiard Avenue'},
                           {'Name': 'Mike', 'School': 'Law', 'Location': 'Fraternity House #22'},
                           {'Name': 'Sally', 'School': 'Engineering', 'Location': '512 Wilson Crescent'}])

print(staff_df.head())
print()
print(student_df.head())
print()
pd.merge(staff_df, student_df, how='left', left_on='Name', right_on='Name')

    Name            Role           Location
0  Kelly  Director of HR       State Street
1  Sally  Course liasion  Washington Avenue
2  James          Grader  Washington Avenue

    Name       School              Location
0  James     Business  1024 Billiard Avenue
1   Mike          Law  Fraternity House #22
2  Sally  Engineering   512 Wilson Crescent

    Name            Role         Location_x       School            Location_y
0  Kelly  Director of HR       State Street          NaN                   NaN
1  Sally  Course liasion  Washington Avenue  Engineering   512 Wilson Crescent
2  James          Grader  Washington Avenue     Business  1024 Billiard Avenue

In [ ]:
staff_df = pd.DataFrame([{'First Name': 'Kelly', 'Last Name': 'Desjardins', 'Role': 'Director of HR'},
                         {'First Name': 'Sally', 'Last Name': 'Brooks', 'Role': 'Course liasion'},
                         {'First Name': 'James', 'Last Name': 'Wilde', 'Role': 'Grader'}])
student_df = pd.DataFrame([{'First Name': 'James', 'Last Name': 'Hammond', 'School': 'Business'},
                           {'First Name': 'Mike', 'Last Name': 'Smith', 'School': 'Law'},
                           {'First Name': 'Sally', 'Last Name': 'Brooks', 'School': 'Engineering'}])

print(staff_df)
print()
print(student_df)
print()
pd.merge(staff_df, student_df, how = 'inner', left_on = ['First Name', 'Last Name'], right_on = ['First Name', 'Last Name'])

  First Name   Last Name            Role
0      Kelly  Desjardins  Director of HR
1      Sally      Brooks  Course liasion
2      James       Wilde          Grader

  First Name Last Name       School
0      James   Hammond     Business
1       Mike     Smith          Law
2      Sally    Brooks  Engineering

  First Name Last Name            Role       School
0      Sally    Brooks  Course liasion  Engineering

### Idiomatic Pandas : Making Code Pandorable

In [ ]:
import pandas as pd

df = pd.read_csv('census.csv')
df

      SUMLEV  REGION  DIVISION  ...  RNETMIG2013  RNETMIG2014 RNETMIG2015
0         40       3         6  ...     1.383282     1.724718    0.712594
1         50       3         6  ...    -2.722002     2.592270   -2.187333
2         50       3         6  ...    22.727626    20.317142   18.293499
3         50       3         6  ...    -7.167664    -3.978583  -10.543299
4         50       3         6  ...    -5.403729     0.754533    1.107861
...      ...     ...       ...  ...          ...          ...         ...
3188      50       4         8  ...    -5.295460   -14.075283  -14.070195
3189      50       4         8  ...    21.160658    16.308671    1.520747
3190      50       4         8  ...    -7.521840   -14.740608  -12.606351
3191      50       4         8  ...    -2.250385   -18.020168    1.441961
3192      50       4         8  ...    12.372583     1.533635    6.935294

[3193 rows x 100 columns]

In [ ]:
(df.where(df['SUMLEV'] == 50)
    .dropna()
    .set_index(['STNAME', 'CTYNAME'])
    .rename(columns = {'ESTIMATESBASE2010' : 'Estimates Base 2010'}))

                           SUMLEV  REGION  ...  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME                            ...
Alabama Autauga County       50.0     3.0  ...     2.592270    -2.187333
        Baldwin County       50.0     3.0  ...    20.317142    18.293499
        Barbour County       50.0     3.0  ...    -3.978583   -10.543299
        Bibb County          50.0     3.0  ...     0.754533     1.107861
        Blount County        50.0     3.0  ...    -1.577232    -0.884411
...                           ...     ...  ...          ...          ...
Wyoming Sweetwater County    50.0     4.0  ...   -14.075283   -14.070195
        Teton County         50.0     4.0  ...    16.308671     1.520747
        Uinta County         50.0     4.0  ...   -14.740608   -12.606351
        Washakie County      50.0     4.0  ...   -18.020168     1.441961
        Weston County        50.0     4.0  ...     1.533635     6.935294

[3142 rows x 98 columns]

In [ ]:
# OR
df = df[df['SUMLEV'] == 50]
df.set_index(['STNAME', 'CTYNAME'], inplace = True)
df.rename(columns = {'ESTIMATESBASE2010' : 'Estimates Base 2010'})

                           SUMLEV  REGION  ...  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME                            ...
Alabama Autauga County         50       3  ...     2.592270    -2.187333
        Baldwin County         50       3  ...    20.317142    18.293499
        Barbour County         50       3  ...    -3.978583   -10.543299
        Bibb County            50       3  ...     0.754533     1.107861
        Blount County          50       3  ...    -1.577232    -0.884411
...                           ...     ...  ...          ...          ...
Wyoming Sweetwater County      50       4  ...   -14.075283   -14.070195
        Teton County           50       4  ...    16.308671     1.520747
        Uinta County           50       4  ...   -14.740608   -12.606351
        Washakie County        50       4  ...   -18.020168     1.441961
        Weston County          50       4  ...     1.533635     6.935294

[3142 rows x 98 columns]

In [ ]:
import numpy as np

def min_max(row):

    data = row[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]

    return pd.Series({'min' : np.min(data), 'max' : np.max(data)})

df.apply(min_max, axis = 1)

                                min       max
STNAME  CTYNAME
Alabama Autauga County      54660.0   55347.0
        Baldwin County     183193.0  203709.0
        Barbour County      26489.0   27341.0
        Bibb County         22512.0   22861.0
        Blount County       57373.0   57776.0
...                             ...       ...
Wyoming Sweetwater County   43593.0   45162.0
        Teton County        21297.0   23125.0
        Uinta County        20822.0   21102.0
        Washakie County      8316.0    8545.0
        Weston County        7065.0    7234.0

[3142 rows x 2 columns]

In [ ]:
import numpy as np

def min_max(row): 

    data = row[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    row['max'] = np.max(data)
    row['min'] = np.min(data)
    
    return row

df.apply(min_max, axis = 1)

                           SUMLEV  REGION  ...       max       min
STNAME  CTYNAME                            ...
Alabama Autauga County       50.0     3.0  ...   55347.0   54660.0
        Baldwin County       50.0     3.0  ...  203709.0  183193.0
        Barbour County       50.0     3.0  ...   27341.0   26489.0
        Bibb County          50.0     3.0  ...   22861.0   22512.0
        Blount County        50.0     3.0  ...   57776.0   57373.0
...                           ...     ...  ...       ...       ...
Wyoming Sweetwater County    50.0     4.0  ...   45162.0   43593.0
        Teton County         50.0     4.0  ...   23125.0   21297.0
        Uinta County         50.0     4.0  ...   21102.0   20822.0
        Washakie County      50.0     4.0  ...    8545.0    8316.0
        Weston County        50.0     4.0  ...    7234.0    7065.0

[3142 rows x 100 columns]

### Group By

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('census.csv')
df = df[df['SUMLEV'] == 50]
df

      SUMLEV  REGION  DIVISION  ...  RNETMIG2013  RNETMIG2014 RNETMIG2015
1         50       3         6  ...    -2.722002     2.592270   -2.187333
2         50       3         6  ...    22.727626    20.317142   18.293499
3         50       3         6  ...    -7.167664    -3.978583  -10.543299
4         50       3         6  ...    -5.403729     0.754533    1.107861
5         50       3         6  ...    -1.402476    -1.577232   -0.884411
...      ...     ...       ...  ...          ...          ...         ...
3188      50       4         8  ...    -5.295460   -14.075283  -14.070195
3189      50       4         8  ...    21.160658    16.308671    1.520747
3190      50       4         8  ...    -7.521840   -14.740608  -12.606351
3191      50       4         8  ...    -2.250385   -18.020168    1.441961
3192      50       4         8  ...    12.372583     1.533635    6.935294

[3142 rows x 100 columns]

In [ ]:
%%timeit -n 10

for state in df['STNAME'].unique():

    avg = np.average(df.where(df['STNAME'] == state).dropna()['CENSUS2010POP'])
    print('Conties in state {} have an average population of {}'.format(state, avg))

Conties in state Alabama have an average population of 71339.34328358209
Conties in state Alaska have an average population of 24490.724137931036
Conties in state Arizona have an average population of 426134.4666666667
Conties in state Arkansas have an average population of 38878.90666666667
Conties in state California have an average population of 642309.5862068966
Conties in state Colorado have an average population of 78581.1875
Conties in state Connecticut have an average population of 446762.125
Conties in state Delaware have an average population of 299311.3333333333
Conties in state District of Columbia have an average population of 601723.0
Conties in state Florida have an average population of 280616.5671641791
Conties in state Georgia have an average population of 60928.63522012578
Conties in state Hawaii have an average population of 272060.2
Conties in state Idaho have an average population of 35626.86363636364
Conties in state Illinois have an average population of 125790.50980392157
Conties in state Indiana have an average population of 70476.10869565218
Conties in state Iowa have an average population of 30771.262626262625
Conties in state Kansas have an average population of 27172.55238095238
Conties in state Kentucky have an average population of 36161.39166666667
Conties in state Louisiana have an average population of 70833.9375
Conties in state Maine have an average population of 83022.5625
Conties in state Maryland have an average population of 240564.66666666666
Conties in state Massachusetts have an average population of 467687.78571428574
Conties in state Michigan have an average population of 119080.0
Conties in state Minnesota have an average population of 60964.65517241379
Conties in state Mississippi have an average population of 36186.54878048781
Conties in state Missouri have an average population of 52077.62608695652
Conties in state Montana have an average population of 17668.125
Conties in state Nebraska have an average population of 19638.075268817203
Conties in state Nevada have an average population of 158855.9411764706
Conties in state New Hampshire have an average population of 131647.0
Conties in state New Jersey have an average population of 418661.61904761905
Conties in state New Mexico have an average population of 62399.36363636364
Conties in state New York have an average population of 312550.03225806454
Conties in state North Carolina have an average population of 95354.83
Conties in state North Dakota have an average population of 12690.396226415094
Conties in state Ohio have an average population of 131096.63636363635
Conties in state Oklahoma have an average population of 48718.844155844155
Conties in state Oregon have an average population of 106418.72222222222
Conties in state Pennsylvania have an average population of 189587.74626865672
Conties in state Rhode Island have an average population of 210513.4
Conties in state South Carolina have an average population of 100551.39130434782
Conties in state South Dakota have an average population of 12336.060606060606
Conties in state Tennessee have an average population of 66801.1052631579
Conties in state Texas have an average population of 98998.27165354331
Conties in state Utah have an average population of 95306.37931034483
Conties in state Vermont have an average population of 44695.78571428572
Conties in state Virginia have an average population of 60111.29323308271
Conties in state Washington have an average population of 172424.10256410256
Conties in state West Virginia have an average population of 33690.8
Conties in state Wisconsin have an average population of 78985.91666666667
Conties in state Wyoming have an average population of 24505.478260869564
Conties in state Alabama have an average population of 71339.34328358209
Conties in state Alaska have an average population of 24490.724137931036
Conties in state Arizona have an average population of 426134.4666666667
Conties in state Arkansas have an average population of 38878.90666666667
Conties in state California have an average population of 642309.5862068966
Conties in state Colorado have an average population of 78581.1875
Conties in state Connecticut have an average population of 446762.125
Conties in state Delaware have an average population of 299311.3333333333
Conties in state District of Columbia have an average population of 601723.0
Conties in state Florida have an average population of 280616.5671641791
Conties in state Georgia have an average population of 60928.63522012578
Conties in state Hawaii have an average population of 272060.2
Conties in state Idaho have an average population of 35626.86363636364
Conties in state Illinois have an average population of 125790.50980392157
Conties in state Indiana have an average population of 70476.10869565218
Conties in state Iowa have an average population of 30771.262626262625
Conties in state Kansas have an average population of 27172.55238095238
Conties in state Kentucky have an average population of 36161.39166666667
Conties in state Louisiana have an average population of 70833.9375
Conties in state Maine have an average population of 83022.5625
Conties in state Maryland have an average population of 240564.66666666666
Conties in state Massachusetts have an average population of 467687.78571428574
Conties in state Michigan have an average population of 119080.0
Conties in state Minnesota have an average population of 60964.65517241379
Conties in state Mississippi have an average population of 36186.54878048781
Conties in state Missouri have an average population of 52077.62608695652
Conties in state Montana have an average population of 17668.125
Conties in state Nebraska have an average population of 19638.075268817203
Conties in state Nevada have an average population of 158855.9411764706
Conties in state New Hampshire have an average population of 131647.0
Conties in state New Jersey have an average population of 418661.61904761905
Conties in state New Mexico have an average population of 62399.36363636364
Conties in state New York have an average population of 312550.03225806454
Conties in state North Carolina have an average population of 95354.83
Conties in state North Dakota have an average population of 12690.396226415094
Conties in state Ohio have an average population of 131096.63636363635
Conties in state Oklahoma have an average population of 48718.844155844155
Conties in state Oregon have an average population of 106418.72222222222
Conties in state Pennsylvania have an average population of 189587.74626865672
Conties in state Rhode Island have an average population of 210513.4
Conties in state South Carolina have an average population of 100551.39130434782
Conties in state South Dakota have an average population of 12336.060606060606
Conties in state Tennessee have an average population of 66801.1052631579
Conties in state Texas have an average population of 98998.27165354331
Conties in state Utah have an average population of 95306.37931034483
Conties in state Vermont have an average population of 44695.78571428572
Conties in state Virginia have an average population of 60111.29323308271
Conties in state Washington have an average population of 172424.10256410256
Conties in state West Virginia have an average population of 33690.8
Conties in state Wisconsin have an average population of 78985.91666666667
Conties in state Wyoming have an average population of 24505.478260869564
Conties in state Alabama have an average population of 71339.34328358209
Conties in state Alaska have an average population of 24490.724137931036
Conties in state Arizona have an average population of 426134.4666666667
Conties in state Arkansas have an average population of 38878.90666666667
Conties in state California have an average population of 642309.5862068966
Conties in state Colorado have an average population of 78581.1875
Conties in state Connecticut have an average population of 446762.125
Conties in state Delaware have an average population of 299311.3333333333
Conties in state District of Columbia have an average population of 601723.0
Conties in state Florida have an average population of 280616.5671641791
Conties in state Georgia have an average population of 60928.63522012578
Conties in state Hawaii have an average population of 272060.2
Conties in state Idaho have an average population of 35626.86363636364
Conties in state Illinois have an average population of 125790.50980392157
Conties in state Indiana have an average population of 70476.10869565218
Conties in state Iowa have an average population of 30771.262626262625
Conties in state Kansas have an average population of 27172.55238095238
Conties in state Kentucky have an average population of 36161.39166666667
Conties in state Louisiana have an average population of 70833.9375
Conties in state Maine have an average population of 83022.5625
Conties in state Maryland have an average population of 240564.66666666666
Conties in state Massachusetts have an average population of 467687.78571428574
Conties in state Michigan have an average population of 119080.0
Conties in state Minnesota have an average population of 60964.65517241379
Conties in state Mississippi have an average population of 36186.54878048781
Conties in state Missouri have an average population of 52077.62608695652
Conties in state Montana have an average population of 17668.125
Conties in state Nebraska have an average population of 19638.075268817203
Conties in state Nevada have an average population of 158855.9411764706
Conties in state New Hampshire have an average population of 131647.0
Conties in state New Jersey have an average population of 418661.61904761905
Conties in state New Mexico have an average population of 62399.36363636364
Conties in state New York have an average population of 312550.03225806454
Conties in state North Carolina have an average population of 95354.83
Conties in state North Dakota have an average population of 12690.396226415094
Conties in state Ohio have an average population of 131096.63636363635
Conties in state Oklahoma have an average population of 48718.844155844155
Conties in state Oregon have an average population of 106418.72222222222
Conties in state Pennsylvania have an average population of 189587.74626865672
Conties in state Rhode Island have an average population of 210513.4
Conties in state South Carolina have an average population of 100551.39130434782
Conties in state South Dakota have an average population of 12336.060606060606
Conties in state Tennessee have an average population of 66801.1052631579
Conties in state Texas have an average population of 98998.27165354331
Conties in state Utah have an average population of 95306.37931034483
Conties in state Vermont have an average population of 44695.78571428572
Conties in state Virginia have an average population of 60111.29323308271
Conties in state Washington have an average population of 172424.10256410256
Conties in state West Virginia have an average population of 33690.8
Conties in state Wisconsin have an average population of 78985.91666666667
Conties in state Wyoming have an average population of 24505.478260869564
Conties in state Alabama have an average population of 71339.34328358209
Conties in state Alaska have an average population of 24490.724137931036
Conties in state Arizona have an average population of 426134.4666666667
Conties in state Arkansas have an average population of 38878.90666666667
Conties in state California have an average population of 642309.5862068966
Conties in state Colorado have an average population of 78581.1875
Conties in state Connecticut have an average population of 446762.125
Conties in state Delaware have an average population of 299311.3333333333
Conties in state District of Columbia have an average population of 601723.0
Conties in state Florida have an average population of 280616.5671641791
Conties in state Georgia have an average population of 60928.63522012578
Conties in state Hawaii have an average population of 272060.2
Conties in state Idaho have an average population of 35626.86363636364
Conties in state Illinois have an average population of 125790.50980392157
Conties in state Indiana have an average population of 70476.10869565218
Conties in state Iowa have an average population of 30771.262626262625
Conties in state Kansas have an average population of 27172.55238095238
Conties in state Kentucky have an average population of 36161.39166666667
Conties in state Louisiana have an average population of 70833.9375
Conties in state Maine have an average population of 83022.5625
Conties in state Maryland have an average population of 240564.66666666666
Conties in state Massachusetts have an average population of 467687.78571428574
Conties in state Michigan have an average population of 119080.0
Conties in state Minnesota have an average population of 60964.65517241379
Conties in state Mississippi have an average population of 36186.54878048781
Conties in state Missouri have an average population of 52077.62608695652
Conties in state Montana have an average population of 17668.125
Conties in state Nebraska have an average population of 19638.075268817203
Conties in state Nevada have an average population of 158855.9411764706
Conties in state New Hampshire have an average population of 131647.0
Conties in state New Jersey have an average population of 418661.61904761905
Conties in state New Mexico have an average population of 62399.36363636364
Conties in state New York have an average population of 312550.03225806454
Conties in state North Carolina have an average population of 95354.83
Conties in state North Dakota have an average population of 12690.396226415094
Conties in state Ohio have an average population of 131096.63636363635
Conties in state Oklahoma have an average population of 48718.844155844155
Conties in state Oregon have an average population of 106418.72222222222
Conties in state Pennsylvania have an average population of 189587.74626865672
Conties in state Rhode Island have an average population of 210513.4
Conties in state South Carolina have an average population of 100551.39130434782
Conties in state South Dakota have an average population of 12336.060606060606
Conties in state Tennessee have an average population of 66801.1052631579
Conties in state Texas have an average population of 98998.27165354331
Conties in state Utah have an average population of 95306.37931034483
Conties in state Vermont have an average population of 44695.78571428572
Conties in state Virginia have an average population of 60111.29323308271
Conties in state Washington have an average population of 172424.10256410256
Conties in state West Virginia have an average population of 33690.8
Conties in state Wisconsin have an average population of 78985.91666666667
Conties in state Wyoming have an average population of 24505.478260869564
Conties in state Alabama have an average population of 71339.34328358209
Conties in state Alaska have an average population of 24490.724137931036
Conties in state Arizona have an average population of 426134.4666666667
Conties in state Arkansas have an average population of 38878.90666666667
Conties in state California have an average population of 642309.5862068966
Conties in state Colorado have an average population of 78581.1875
Conties in state Connecticut have an average population of 446762.125
Conties in state Delaware have an average population of 299311.3333333333
Conties in state District of Columbia have an average population of 601723.0
Conties in state Florida have an average population of 280616.5671641791
Conties in state Georgia have an average population of 60928.63522012578
Conties in state Hawaii have an average population of 272060.2
Conties in state Idaho have an average population of 35626.86363636364
Conties in state Illinois have an average population of 125790.50980392157
Conties in state Indiana have an average population of 70476.10869565218
Conties in state Iowa have an average population of 30771.262626262625
Conties in state Kansas have an average population of 27172.55238095238
Conties in state Kentucky have an average population of 36161.39166666667
Conties in state Louisiana have an average population of 70833.9375
Conties in state Maine have an average population of 83022.5625
Conties in state Maryland have an average population of 240564.66666666666
Conties in state Massachusetts have an average population of 467687.78571428574
Conties in state Michigan have an average population of 119080.0
Conties in state Minnesota have an average population of 60964.65517241379
Conties in state Mississippi have an average population of 36186.54878048781
Conties in state Missouri have an average population of 52077.62608695652
Conties in state Montana have an average population of 17668.125
Conties in state Nebraska have an average population of 19638.075268817203
Conties in state Nevada have an average population of 158855.9411764706
Conties in state New Hampshire have an average population of 131647.0
Conties in state New Jersey have an average population of 418661.61904761905
Conties in state New Mexico have an average population of 62399.36363636364
Conties in state New York have an average population of 312550.03225806454
Conties in state North Carolina have an average population of 95354.83
Conties in state North Dakota have an average population of 12690.396226415094
Conties in state Ohio have an average population of 131096.63636363635
Conties in state Oklahoma have an average population of 48718.844155844155
Conties in state Oregon have an average population of 106418.72222222222
Conties in state Pennsylvania have an average population of 189587.74626865672
Conties in state Rhode Island have an average population of 210513.4
Conties in state South Carolina have an average population of 100551.39130434782
Conties in state South Dakota have an average population of 12336.060606060606
Conties in state Tennessee have an average population of 66801.1052631579
Conties in state Texas have an average population of 98998.27165354331
Conties in state Utah have an average population of 95306.37931034483
Conties in state Vermont have an average population of 44695.78571428572
Conties in state Virginia have an average population of 60111.29323308271
Conties in state Washington have an average population of 172424.10256410256
Conties in state West Virginia have an average population of 33690.8
Conties in state Wisconsin have an average population of 78985.91666666667
Conties in state Wyoming have an average population of 24505.478260869564
Conties in state Alabama have an average population of 71339.34328358209
Conties in state Alaska have an average population of 24490.724137931036
Conties in state Arizona have an average population of 426134.4666666667
Conties in state Arkansas have an average population of 38878.90666666667
Conties in state California have an average population of 642309.5862068966
Conties in state Colorado have an average population of 78581.1875
Conties in state Connecticut have an average population of 446762.125
Conties in state Delaware have an average population of 299311.3333333333
Conties in state District of Columbia have an average population of 601723.0
Conties in state Florida have an average population of 280616.5671641791
Conties in state Georgia have an average population of 60928.63522012578
Conties in state Hawaii have an average population of 272060.2
Conties in state Idaho have an average population of 35626.86363636364
Conties in state Illinois have an average population of 125790.50980392157
Conties in state Indiana have an average population of 70476.10869565218
Conties in state Iowa have an average population of 30771.262626262625
Conties in state Kansas have an average population of 27172.55238095238
Conties in state Kentucky have an average population of 36161.39166666667
Conties in state Louisiana have an average population of 70833.9375

In [ ]:
%%timeit -n 10

for group, frame in df.groupby('STNAME'):

    avg = np.average(frame['CENSUS2010POP'])
    print('Counties in state {} have an average population of {}'.format(group, avg))

Counties in state Alabama have an average population of 71339.34328358209
Counties in state Alaska have an average population of 24490.724137931036
Counties in state Arizona have an average population of 426134.4666666667
Counties in state Arkansas have an average population of 38878.90666666667
Counties in state California have an average population of 642309.5862068966
Counties in state Colorado have an average population of 78581.1875
Counties in state Connecticut have an average population of 446762.125
Counties in state Delaware have an average population of 299311.3333333333
Counties in state District of Columbia have an average population of 601723.0
Counties in state Florida have an average population of 280616.5671641791
Counties in state Georgia have an average population of 60928.63522012578
Counties in state Hawaii have an average population of 272060.2
Counties in state Idaho have an average population of 35626.86363636364
Counties in state Illinois have an average population of 125790.50980392157
Counties in state Indiana have an average population of 70476.10869565218
Counties in state Iowa have an average population of 30771.262626262625
Counties in state Kansas have an average population of 27172.55238095238
Counties in state Kentucky have an average population of 36161.39166666667
Counties in state Louisiana have an average population of 70833.9375
Counties in state Maine have an average population of 83022.5625
Counties in state Maryland have an average population of 240564.66666666666
Counties in state Massachusetts have an average population of 467687.78571428574
Counties in state Michigan have an average population of 119080.0
Counties in state Minnesota have an average population of 60964.65517241379
Counties in state Mississippi have an average population of 36186.54878048781
Counties in state Missouri have an average population of 52077.62608695652
Counties in state Montana have an average population of 17668.125
Counties in state Nebraska have an average population of 19638.075268817203
Counties in state Nevada have an average population of 158855.9411764706
Counties in state New Hampshire have an average population of 131647.0
Counties in state New Jersey have an average population of 418661.61904761905
Counties in state New Mexico have an average population of 62399.36363636364
Counties in state New York have an average population of 312550.03225806454
Counties in state North Carolina have an average population of 95354.83
Counties in state North Dakota have an average population of 12690.396226415094
Counties in state Ohio have an average population of 131096.63636363635
Counties in state Oklahoma have an average population of 48718.844155844155
Counties in state Oregon have an average population of 106418.72222222222
Counties in state Pennsylvania have an average population of 189587.74626865672
Counties in state Rhode Island have an average population of 210513.4
Counties in state South Carolina have an average population of 100551.39130434782
Counties in state South Dakota have an average population of 12336.060606060606
Counties in state Tennessee have an average population of 66801.1052631579
Counties in state Texas have an average population of 98998.27165354331
Counties in state Utah have an average population of 95306.37931034483
Counties in state Vermont have an average population of 44695.78571428572
Counties in state Virginia have an average population of 60111.29323308271
Counties in state Washington have an average population of 172424.10256410256
Counties in state West Virginia have an average population of 33690.8
Counties in state Wisconsin have an average population of 78985.91666666667
Counties in state Wyoming have an average population of 24505.478260869564
Counties in state Alabama have an average population of 71339.34328358209
Counties in state Alaska have an average population of 24490.724137931036
Counties in state Arizona have an average population of 426134.4666666667
Counties in state Arkansas have an average population of 38878.90666666667
Counties in state California have an average population of 642309.5862068966
Counties in state Colorado have an average population of 78581.1875
Counties in state Connecticut have an average population of 446762.125
Counties in state Delaware have an average population of 299311.3333333333
Counties in state District of Columbia have an average population of 601723.0
Counties in state Florida have an average population of 280616.5671641791
Counties in state Georgia have an average population of 60928.63522012578
Counties in state Hawaii have an average population of 272060.2
Counties in state Idaho have an average population of 35626.86363636364
Counties in state Illinois have an average population of 125790.50980392157
Counties in state Indiana have an average population of 70476.10869565218
Counties in state Iowa have an average population of 30771.262626262625
Counties in state Kansas have an average population of 27172.55238095238
Counties in state Kentucky have an average population of 36161.39166666667
Counties in state Louisiana have an average population of 70833.9375
Counties in state Maine have an average population of 83022.5625
Counties in state Maryland have an average population of 240564.66666666666
Counties in state Massachusetts have an average population of 467687.78571428574
Counties in state Michigan have an average population of 119080.0
Counties in state Minnesota have an average population of 60964.65517241379
Counties in state Mississippi have an average population of 36186.54878048781
Counties in state Missouri have an average population of 52077.62608695652
Counties in state Montana have an average population of 17668.125
Counties in state Nebraska have an average population of 19638.075268817203
Counties in state Nevada have an average population of 158855.9411764706
Counties in state New Hampshire have an average population of 131647.0
Counties in state New Jersey have an average population of 418661.61904761905
Counties in state New Mexico have an average population of 62399.36363636364
Counties in state New York have an average population of 312550.03225806454
Counties in state North Carolina have an average population of 95354.83
Counties in state North Dakota have an average population of 12690.396226415094
Counties in state Ohio have an average population of 131096.63636363635
Counties in state Oklahoma have an average population of 48718.844155844155
Counties in state Oregon have an average population of 106418.72222222222
Counties in state Pennsylvania have an average population of 189587.74626865672
Counties in state Rhode Island have an average population of 210513.4
Counties in state South Carolina have an average population of 100551.39130434782
Counties in state South Dakota have an average population of 12336.060606060606
Counties in state Tennessee have an average population of 66801.1052631579
Counties in state Texas have an average population of 98998.27165354331
Counties in state Utah have an average population of 95306.37931034483
Counties in state Vermont have an average population of 44695.78571428572
Counties in state Virginia have an average population of 60111.29323308271
Counties in state Washington have an average population of 172424.10256410256
Counties in state West Virginia have an average population of 33690.8
Counties in state Wisconsin have an average population of 78985.91666666667
Counties in state Wyoming have an average population of 24505.478260869564
Counties in state Alabama have an average population of 71339.34328358209
Counties in state Alaska have an average population of 24490.724137931036
Counties in state Arizona have an average population of 426134.4666666667
Counties in state Arkansas have an average population of 38878.90666666667
Counties in state California have an average population of 642309.5862068966
Counties in state Colorado have an average population of 78581.1875
Counties in state Connecticut have an average population of 446762.125
Counties in state Delaware have an average population of 299311.3333333333
Counties in state District of Columbia have an average population of 601723.0
Counties in state Florida have an average population of 280616.5671641791
Counties in state Georgia have an average population of 60928.63522012578
Counties in state Hawaii have an average population of 272060.2
Counties in state Idaho have an average population of 35626.86363636364
Counties in state Illinois have an average population of 125790.50980392157
Counties in state Indiana have an average population of 70476.10869565218
Counties in state Iowa have an average population of 30771.262626262625
Counties in state Kansas have an average population of 27172.55238095238
Counties in state Kentucky have an average population of 36161.39166666667
Counties in state Louisiana have an average population of 70833.9375
Counties in state Maine have an average population of 83022.5625
Counties in state Maryland have an average population of 240564.66666666666
Counties in state Massachusetts have an average population of 467687.78571428574
Counties in state Michigan have an average population of 119080.0
Counties in state Minnesota have an average population of 60964.65517241379
Counties in state Mississippi have an average population of 36186.54878048781
Counties in state Missouri have an average population of 52077.62608695652
Counties in state Montana have an average population of 17668.125
Counties in state Nebraska have an average population of 19638.075268817203
Counties in state Nevada have an average population of 158855.9411764706
Counties in state New Hampshire have an average population of 131647.0
Counties in state New Jersey have an average population of 418661.61904761905
Counties in state New Mexico have an average population of 62399.36363636364
Counties in state New York have an average population of 312550.03225806454
Counties in state North Carolina have an average population of 95354.83
Counties in state North Dakota have an average population of 12690.396226415094
Counties in state Ohio have an average population of 131096.63636363635
Counties in state Oklahoma have an average population of 48718.844155844155
Counties in state Oregon have an average population of 106418.72222222222
Counties in state Pennsylvania have an average population of 189587.74626865672
Counties in state Rhode Island have an average population of 210513.4
Counties in state South Carolina have an average population of 100551.39130434782
Counties in state South Dakota have an average population of 12336.060606060606
Counties in state Tennessee have an average population of 66801.1052631579
Counties in state Texas have an average population of 98998.27165354331
Counties in state Utah have an average population of 95306.37931034483
Counties in state Vermont have an average population of 44695.78571428572
Counties in state Virginia have an average population of 60111.29323308271
Counties in state Washington have an average population of 172424.10256410256
Counties in state West Virginia have an average population of 33690.8
Counties in state Wisconsin have an average population of 78985.91666666667
Counties in state Wyoming have an average population of 24505.478260869564
Counties in state Alabama have an average population of 71339.34328358209
Counties in state Alaska have an average population of 24490.724137931036
Counties in state Arizona have an average population of 426134.4666666667
Counties in state Arkansas have an average population of 38878.90666666667
Counties in state California have an average population of 642309.5862068966
Counties in state Colorado have an average population of 78581.1875
Counties in state Connecticut have an average population of 446762.125
Counties in state Delaware have an average population of 299311.3333333333
Counties in state District of Columbia have an average population of 601723.0
Counties in state Florida have an average population of 280616.5671641791
Counties in state Georgia have an average population of 60928.63522012578
Counties in state Hawaii have an average population of 272060.2
Counties in state Idaho have an average population of 35626.86363636364
Counties in state Illinois have an average population of 125790.50980392157
Counties in state Indiana have an average population of 70476.10869565218
Counties in state Iowa have an average population of 30771.262626262625
Counties in state Kansas have an average population of 27172.55238095238
Counties in state Kentucky have an average population of 36161.39166666667
Counties in state Louisiana have an average population of 70833.9375
Counties in state Maine have an average population of 83022.5625
Counties in state Maryland have an average population of 240564.66666666666
Counties in state Massachusetts have an average population of 467687.78571428574
Counties in state Michigan have an average population of 119080.0
Counties in state Minnesota have an average population of 60964.65517241379
Counties in state Mississippi have an average population of 36186.54878048781
Counties in state Missouri have an average population of 52077.62608695652
Counties in state Montana have an average population of 17668.125
Counties in state Nebraska have an average population of 19638.075268817203
Counties in state Nevada have an average population of 158855.9411764706
Counties in state New Hampshire have an average population of 131647.0
Counties in state New Jersey have an average population of 418661.61904761905
Counties in state New Mexico have an average population of 62399.36363636364
Counties in state New York have an average population of 312550.03225806454
Counties in state North Carolina have an average population of 95354.83
Counties in state North Dakota have an average population of 12690.396226415094
Counties in state Ohio have an average population of 131096.63636363635
Counties in state Oklahoma have an average population of 48718.844155844155
Counties in state Oregon have an average population of 106418.72222222222
Counties in state Pennsylvania have an average population of 189587.74626865672
Counties in state Rhode Island have an average population of 210513.4
Counties in state South Carolina have an average population of 100551.39130434782
Counties in state South Dakota have an average population of 12336.060606060606
Counties in state Tennessee have an average population of 66801.1052631579
Counties in state Texas have an average population of 98998.27165354331
Counties in state Utah have an average population of 95306.37931034483
Counties in state Vermont have an average population of 44695.78571428572
Counties in state Virginia have an average population of 60111.29323308271
Counties in state Washington have an average population of 172424.10256410256
Counties in state West Virginia have an average population of 33690.8
Counties in state Wisconsin have an average population of 78985.91666666667
Counties in state Wyoming have an average population of 24505.478260869564
Counties in state Alabama have an average population of 71339.34328358209
Counties in state Alaska have an average population of 24490.724137931036
Counties in state Arizona have an average population of 426134.4666666667
Counties in state Arkansas have an average population of 38878.90666666667
Counties in state California have an average population of 642309.5862068966
Counties in state Colorado have an average population of 78581.1875
Counties in state Connecticut have an average population of 446762.125
Counties in state Delaware have an average population of 299311.3333333333
Counties in state District of Columbia have an average population of 601723.0
Counties in state Florida have an average population of 280616.5671641791
Counties in state Georgia have an average population of 60928.63522012578
Counties in state Hawaii have an average population of 272060.2
Counties in state Idaho have an average population of 35626.86363636364
Counties in state Illinois have an average population of 125790.50980392157
Counties in state Indiana have an average population of 70476.10869565218
Counties in state Iowa have an average population of 30771.262626262625
Counties in state Kansas have an average population of 27172.55238095238
Counties in state Kentucky have an average population of 36161.39166666667
Counties in state Louisiana have an average population of 70833.9375
Counties in state Maine have an average population of 83022.5625
Counties in state Maryland have an average population of 240564.66666666666
Counties in state Massachusetts have an average population of 467687.78571428574
Counties in state Michigan have an average population of 119080.0
Counties in state Minnesota have an average population of 60964.65517241379
Counties in state Mississippi have an average population of 36186.54878048781
Counties in state Missouri have an average population of 52077.62608695652
Counties in state Montana have an average population of 17668.125
Counties in state Nebraska have an average population of 19638.075268817203
Counties in state Nevada have an average population of 158855.9411764706
Counties in state New Hampshire have an average population of 131647.0
Counties in state New Jersey have an average population of 418661.61904761905
Counties in state New Mexico have an average population of 62399.36363636364
Counties in state New York have an average population of 312550.03225806454
Counties in state North Carolina have an average population of 95354.83
Counties in state North Dakota have an average population of 12690.396226415094
Counties in state Ohio have an average population of 131096.63636363635
Counties in state Oklahoma have an average population of 48718.844155844155
Counties in state Oregon have an average population of 106418.72222222222
Counties in state Pennsylvania have an average population of 189587.74626865672
Counties in state Rhode Island have an average population of 210513.4
Counties in state South Carolina have an average population of 100551.39130434782
Counties in state South Dakota have an average population of 12336.060606060606
Counties in state Tennessee have an average population of 66801.1052631579
Counties in state Texas have an average population of 98998.27165354331
Counties in state Utah have an average population of 95306.37931034483
Counties in state Vermont have an average population of 44695.78571428572
Counties in state Virginia have an average population of 60111.29323308271
Counties in state Washington have an average population of 172424.10256410256
Counties in state West Virginia have an average population of 33690.8
Counties in state Wisconsin have an average population of 78985.91666666667
Counties in state Wyoming have an average population of 24505.478260869564
Counties in state Alabama have an average population of 71339.34328358209
Counties in state Alaska have an average population of 24490.724137931036
Counties in state Arizona have an average population of 426134.4666666667
Counties in state Arkansas have an average population of 38878.90666666667
Counties in state California have an average population of 642309.5862068966
Counties in state Colorado have an average population of 78581.1875
Counties in state Connecticut have an average population of 446762.125
Counties in state Delaware have an average population of 299311.3333333333
Counties in state District of Columbia have an average population of 601723.0
Counties in state Florida have an average population of 280616.5671641791
Counties in state Georgia have an average population of 60928.63522012578
Counties in state Hawaii have an average population of 272060.2
Counties in state Idaho have an average population of 35626.86363636364
Counties in state Illinois have an average population of 125790.50980392157
Counties in state Indiana have an average population of 70476.10869565218

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('census.csv')
df = df[df['SUMLEV'] == 50]

for group, frame in df.groupby('STNAME'):

    avg = np.average(frame['CENSUS2010POP'])

df = df.set_index('STNAME')

def fun(item):

    if item[0] < 'M':
        return 0
    if item[0] < 'Q':
        return 1
    return 2

print(df.groupby(fun))

for group, frame in df.groupby(fun):
    print('There are {} records in group {} for processing'.format(len(frame), group))

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7f63b33340b8>
There are 1177 records in group 0 for processing
There are 1134 records in group 1 for processing
There are 831 records in group 2 for processing

In [ ]:
df = pd.read_csv('census.csv')
df = df[df['SUMLEV'] == 50]
df.groupby('STNAME').agg({'CENSUS2010POP' : np.average})

                      CENSUS2010POP
STNAME
Alabama                71339.343284
Alaska                 24490.724138
Arizona               426134.466667
Arkansas               38878.906667
California            642309.586207
Colorado               78581.187500
Connecticut           446762.125000
Delaware              299311.333333
District of Columbia  601723.000000
Florida               280616.567164
Georgia                60928.635220
Hawaii                272060.200000
Idaho                  35626.863636
Illinois              125790.509804
Indiana                70476.108696
Iowa                   30771.262626
Kansas                 27172.552381
Kentucky               36161.391667
Louisiana              70833.937500
Maine                  83022.562500
Maryland              240564.666667
Massachusetts         467687.785714
Michigan              119080.000000
Minnesota              60964.655172
Mississippi            36186.548780
Missouri               52077.626087
Montana                17668.125000
Nebraska               19638.075269
Nevada                158855.941176
New Hampshire         131647.000000
New Jersey            418661.619048
New Mexico             62399.363636
New York              312550.032258
North Carolina         95354.830000
North Dakota           12690.396226
Ohio                  131096.636364
Oklahoma               48718.844156
Oregon                106418.722222
Pennsylvania          189587.746269
Rhode Island          210513.400000
South Carolina        100551.391304
South Dakota           12336.060606
Tennessee              66801.105263
Texas                  98998.271654
Utah                   95306.379310
Vermont                44695.785714
Virginia               60111.293233
Washington            172424.102564
West Virginia          33690.800000
Wisconsin              78985.916667
Wyoming                24505.478261

In [ ]:
print(type(df.groupby(level = 0)['POPESTIMATE2010', 'POPESTIMATE2011']))
print(type(df.groupby(level = 0)['POPESTIMATE2010']))

pandas.core.groupby.generic.DataFrameGroupBy
pandas.core.groupby.generic.SeriesGroupBy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.